### ISSUE TITLE
Project maturity questions

### ISSUE THREAD

**Issue by doron-cohen** [protoconf/protoconf#126]
Hi,

I am very interested in this project to help manage configurations in our company. I just wanted to ask a few questions about the maturity of the project.
1. Is it still actively maintained? I see some changes are made but long time since last release.
2. Is it used in production anywhere?
3. Any plans on improving documentation? I sure could help here if we get to use this.

I really like the simplicity and approach BTW. I also think this is a very important tool that solves a complicated and hard issue. Thanks for the project!

**Comment by smintz** [comment]
I recently updated the docs under /docs of this repo, these are now get published on https://protoconf.github.io/protoconf and any improvement will be highly appreciated :)

I am not currently aware of anyone using it in production but I do know some folks (mostly ex-facebookers who are familiar with configerator) who are evaluating it for production use.

If you want to run it in production I will be happy to provide any assistance needed and will be happy to receive feedback so we can improve it.

**Comment by doron-cohen** [comment]
Nice to hear. We are planning on using this project in production partially. I am evaluating it right now. For the first step we might avoid using a KV store and upload the materialized JSON files to a bucket.

Docs are great. I added a link to the readme in #129

**Comment by smintz** [comment]
Cool, note that by using an object store you will lose the ability to utilize the agent for config change subscription, so you will need to develop the mechanism yourself or to restart your service in order to consume changes...

If you need, I can add support for redis and maybe even Postgres...

**Comment by doron-cohen** [comment]
Yes we are aware of the limitation. We wanted to first setup and stabilize the schema and process and only then work to deploy a highly available Consul. We also wanted to eliminate moving parts since if the KV store is down we can't configure our services.

I think I got what I need from this ticket. I will close it for now. Thanks again.
