### ISSUE TITLE
Keys case is turned into camel case after compilation

### ISSUE THREAD

**Issue by doron-cohen** [protoconf/protoconf#128]
Hi

I have a `.proto` schema:
```protobuf
message ProcessedDataStream {
  oneof stream {
    GcsFilesStream gcs_files = 4;
  }
}
```

I added a config using a `.pconf` file:
```starlark
stream = ProcessedDataStream(
    gcs_files=GcsFilesStream(bucket="climacell-ENV-hrrr-raw-us"),
)
```

But the result switched `gcs_files` to `gcsFiles`:
```json
{
    "protoFile": "uniconf/ingest/v1/schema.proto",
    "value": {
            ...
            "gcsFiles": {
                "bucket": "climacell-ENV-hrrr-raw-us"
            }
        }
    }
}
```

Is this expected? Is this because of the `oneof`?

**Comment by doron-cohen** [comment]
I just checked and it's not related to the `oneof`. It also happens on regular fields.

**Comment by doron-cohen** [comment]
Thanks @smintz. So I guess it will also generate code for other languages with the same case? Will Python, Go and other stubs generated with `protobuf` also use this case?

**Comment by smintz** [comment]
Correct

**Comment by smintz** [comment]
Actually this is a bit misleading... the generated code of protobuf will result which are as the convention for that language. So python will be `sneak_case` but Golang will be `CapitalCase` and Java will be `camelCase`

**Comment by smintz** [comment]
I suggest you will review protobuf and grpc documentation to learn more

**Comment by smintz** [comment]
I suggest you will review protobuf and grpc documentation to learn more

**Comment by doron-cohen** [comment]
Thanks @smintz I will
