### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by smintz** [protoconf/protoconf#332]
The project isn't consistent when it comes to logging. We should choose a logging library that will give users a standard logs which will allow them integrate the logs into their preferred logging aggregator and filter them to their needs.

Some popular options:
1. logrus
2. zap
3. zerolog

opinions are welcome in this discussion :)

**Comment by buzzdan** [comment]
> Many fantastic alternatives have sprung up. Logrus would look like those, had it been re-designed with what we know about structured logging in Go today. Check out, for example, [Zerolog](https://github.com/rs/zerolog), [Zap](https://github.com/uber-go/zap), and [Apex](https://github.com/apex/log).

^^ Logrus ^^

**Comment by avivl** [comment]
Logrus is in maintenance-mode.

**Comment by avivl** [comment]
Go 1.21 (currently RC) will have slog https://pkg.go.dev/log/slog@master

**Comment by smintz** [comment]
We decided to settle on `slog`. Some parts already migrated. Need to migrate all parts for consistency.
